# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'imu.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLCDNumber,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTextEdit,
    QWidget)

class IMU_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1265, 802)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 10, 841, 581))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.textEdit = QTextEdit(self.frame)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 0, 841, 51))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 211, 31))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(20)
        self.label.setFont(font)
        self.groupBox = QGroupBox(self.frame)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 80, 771, 321))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(14)
        self.groupBox.setFont(font1)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(190, 30, 21, 31))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(12)
        self.label_3.setFont(font2)
        self.lcdNumber_4 = QLCDNumber(self.groupBox)
        self.lcdNumber_4.setObjectName(u"lcdNumber_4")
        self.lcdNumber_4.setGeometry(QRect(350, 70, 201, 41))
        self.lcdNumber = QLCDNumber(self.groupBox)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(140, 70, 201, 41))
        self.lcdNumber_5 = QLCDNumber(self.groupBox)
        self.lcdNumber_5.setObjectName(u"lcdNumber_5")
        self.lcdNumber_5.setGeometry(QRect(560, 70, 201, 41))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(420, 30, 21, 31))
        self.label_6.setFont(font2)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(640, 30, 21, 31))
        self.label_7.setFont(font2)
        self.lcdNumber_8 = QLCDNumber(self.groupBox)
        self.lcdNumber_8.setObjectName(u"lcdNumber_8")
        self.lcdNumber_8.setGeometry(QRect(560, 150, 201, 41))
        self.lcdNumber_10 = QLCDNumber(self.groupBox)
        self.lcdNumber_10.setObjectName(u"lcdNumber_10")
        self.lcdNumber_10.setGeometry(QRect(560, 240, 201, 41))
        self.lcdNumber_11 = QLCDNumber(self.groupBox)
        self.lcdNumber_11.setObjectName(u"lcdNumber_11")
        self.lcdNumber_11.setGeometry(QRect(350, 150, 201, 41))
        self.lcdNumber_12 = QLCDNumber(self.groupBox)
        self.lcdNumber_12.setObjectName(u"lcdNumber_12")
        self.lcdNumber_12.setGeometry(QRect(350, 240, 201, 41))
        self.lcdNumber_2 = QLCDNumber(self.groupBox)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(140, 150, 201, 41))
        self.lcdNumber_3 = QLCDNumber(self.groupBox)
        self.lcdNumber_3.setObjectName(u"lcdNumber_3")
        self.lcdNumber_3.setGeometry(QRect(140, 240, 201, 41))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 150, 121, 31))
        self.label_4.setFont(font2)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 70, 121, 31))
        self.label_13.setFont(font2)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 240, 121, 31))
        self.label_5.setFont(font2)
        self.groupBox_3 = QGroupBox(self.frame)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(30, 420, 771, 141))
        self.groupBox_3.setFont(font1)
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 40, 61, 31))
        self.label_8.setFont(font2)
        self.lcdNumber_7 = QLCDNumber(self.groupBox_3)
        self.lcdNumber_7.setObjectName(u"lcdNumber_7")
        self.lcdNumber_7.setGeometry(QRect(270, 70, 201, 41))
        self.lcdNumber_9 = QLCDNumber(self.groupBox_3)
        self.lcdNumber_9.setObjectName(u"lcdNumber_9")
        self.lcdNumber_9.setGeometry(QRect(10, 70, 201, 41))
        self.lcdNumber_13 = QLCDNumber(self.groupBox_3)
        self.lcdNumber_13.setObjectName(u"lcdNumber_13")
        self.lcdNumber_13.setGeometry(QRect(510, 70, 201, 41))
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(280, 40, 61, 31))
        self.label_9.setFont(font2)
        self.label_12 = QLabel(self.groupBox_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(510, 40, 61, 31))
        self.label_12.setFont(font2)
        self.groupBox.raise_()
        self.textEdit.raise_()
        self.label.raise_()
        self.groupBox_3.raise_()
        self.satelliteVisualization = QOpenGLWidget(self.centralwidget)
        self.satelliteVisualization.setObjectName(u"satelliteVisualization")
        self.satelliteVisualization.setGeometry(QRect(890, 40, 341, 201))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(890, 10, 191, 31))
        self.label_11.setFont(font2)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 610, 841, 121))
        self.pushButton = QPushButton(self.groupBox_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(530, 50, 291, 51))
        self.pushButton.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(15, 102, 28);")
        self.lcdNumber_6 = QLCDNumber(self.groupBox_2)
        self.lcdNumber_6.setObjectName(u"lcdNumber_6")
        self.lcdNumber_6.setGeometry(QRect(20, 60, 201, 41))
        self.lcdNumber_14 = QLCDNumber(self.groupBox_2)
        self.lcdNumber_14.setObjectName(u"lcdNumber_14")
        self.lcdNumber_14.setGeometry(QRect(260, 60, 201, 41))
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 30, 101, 31))
        self.label_10.setFont(font2)
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(260, 30, 131, 31))
        self.label_14.setFont(font2)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(890, 280, 341, 201))
        self.widget.setStyleSheet(u"background-color: rgb(204, 204, 204);")
        self.widget_2 = QWidget(self.widget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(210, 140, 341, 201))
        self.widget_2.setStyleSheet(u"background-color: rgb(204, 204, 204);")
        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(890, 520, 341, 211))
        self.widget_3.setStyleSheet(u"background-color: rgb(204, 204, 204);")
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(890, 250, 341, 31))
        self.label_15.setFont(font2)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(890, 490, 191, 31))
        self.label_16.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # Just label for everything, can even translate it if necessary
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"IMU Reading", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Raw Values", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Accelerometer", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Gyroscope", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Magnetometer", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Orientation", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Roll", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Yaw", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Orientation Visualizer", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Attitude Command", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Command", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Orientation", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Angular velocity", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Tilt visualizer ( pitch + roll )", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Heading visualizer (Yaw)", None))
