# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'summary.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QGroupBox,
    QLCDNumber, QLabel, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QStatusBar, QTextEdit, QWidget)

class Ui_MainWindow(object):
    # def __init__(self, QMainWindowObj):
    #     super().__init__()
    #     self.setupUi(self)
    #     self.setWindowTitle("Test title")


    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1265, 802)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(30, 10, 261, 721))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.textEdit = QTextEdit(self.frame)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 0, 261, 51))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 211, 31))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(20)
        self.label.setFont(font)
        self.lcdNumber = QLCDNumber(self.frame)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(30, 130, 201, 41))
        self.lcdNumber_2 = QLCDNumber(self.frame)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(30, 310, 201, 41))
        self.lcdNumber_3 = QLCDNumber(self.frame)
        self.lcdNumber_3.setObjectName(u"lcdNumber_3")
        self.lcdNumber_3.setGeometry(QRect(30, 220, 201, 41))
        self.lcdNumber_4 = QLCDNumber(self.frame)
        self.lcdNumber_4.setObjectName(u"lcdNumber_4")
        self.lcdNumber_4.setGeometry(QRect(30, 510, 201, 41))
        self.lcdNumber_5 = QLCDNumber(self.frame)
        self.lcdNumber_5.setObjectName(u"lcdNumber_5")
        self.lcdNumber_5.setGeometry(QRect(30, 620, 201, 41))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 100, 121, 31))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(12)
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 190, 121, 31))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 280, 121, 31))
        self.label_5.setFont(font1)
        self.groupBox = QGroupBox(self.frame)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 70, 231, 321))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(14)
        self.groupBox.setFont(font2)
        self.groupBox_2 = QGroupBox(self.frame)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 430, 221, 271))
        self.groupBox_2.setFont(font2)
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 121, 31))
        self.label_6.setFont(font1)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 160, 161, 31))
        self.label_7.setFont(font1)
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.textEdit.raise_()
        self.label.raise_()
        self.lcdNumber.raise_()
        self.lcdNumber_2.raise_()
        self.lcdNumber_3.raise_()
        self.lcdNumber_4.raise_()
        self.lcdNumber_5.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(330, 10, 571, 491))
        self.graphicsView.setAutoFillBackground(True)
        brush = QBrush(QColor(255, 124, 234, 255))
        brush.setStyle(Qt.NoBrush)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView_4 = QGraphicsView(self.centralwidget)
        self.graphicsView_4.setObjectName(u"graphicsView_4")
        self.graphicsView_4.setGeometry(QRect(930, 10, 271, 291))
        self.graphicsView_4.setAutoFillBackground(True)
        brush1 = QBrush(QColor(255, 124, 234, 255))
        brush1.setStyle(Qt.NoBrush)
        self.graphicsView_4.setBackgroundBrush(brush1)
        self.graphicsView_5 = QGraphicsView(self.centralwidget)
        self.graphicsView_5.setObjectName(u"graphicsView_5")
        self.graphicsView_5.setGeometry(QRect(930, 320, 271, 411))
        self.graphicsView_5.setAutoFillBackground(True)
        self.graphicsView_5.setStyleSheet(u"background-color: rgb(225, 225, 225);")
        brush2 = QBrush(QColor(255, 124, 234, 255))
        brush2.setStyle(Qt.NoBrush)
        self.graphicsView_5.setBackgroundBrush(brush2)
        self.satelliteVisualization = QOpenGLWidget(self.centralwidget)
        self.satelliteVisualization.setObjectName(u"satelliteVisualization")
        self.satelliteVisualization.setGeometry(QRect(330, 530, 271, 200))
        self.Connection = QWidget(self.centralwidget)
        self.Connection.setObjectName(u"Connection")
        self.Connection.setGeometry(QRect(930, 320, 271, 51))
        font3 = QFont()
        font3.setPointSize(14)
        self.Connection.setFont(font3)
        self.Connection.setStyleSheet(u"background-color: rgb(211, 211, 211);")
        self.label_2 = QLabel(self.Connection)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 261, 31))
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(16)
        self.label_2.setFont(font4)
        self.label_2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.Connection_2 = QWidget(self.centralwidget)
        self.Connection_2.setObjectName(u"Connection_2")
        self.Connection_2.setGeometry(QRect(930, 10, 271, 51))
        self.Connection_2.setFont(font3)
        self.Connection_2.setStyleSheet(u"background-color: rgb(211, 211, 211);")
        self.label_10 = QLabel(self.Connection_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 10, 231, 31))
        self.label_10.setFont(font4)
        self.label_10.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(950, 390, 231, 261))
        self.groupBox_3.setFont(font2)
        self.groupBox_3.setStyleSheet(u"background-color: rgb(112, 112, 112);")
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 50, 121, 31))
        self.label_8.setFont(font1)
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 140, 161, 31))
        self.label_9.setFont(font1)
        self.lcdNumber_6 = QLCDNumber(self.groupBox_3)
        self.lcdNumber_6.setObjectName(u"lcdNumber_6")
        self.lcdNumber_6.setGeometry(QRect(10, 80, 201, 41))
        self.lcdNumber_7 = QLCDNumber(self.groupBox_3)
        self.lcdNumber_7.setObjectName(u"lcdNumber_7")
        self.lcdNumber_7.setGeometry(QRect(20, 180, 201, 41))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(950, 670, 231, 41))
        self.pushButton_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 107, 29);")
        self.graphicsView_6 = QGraphicsView(self.centralwidget)
        self.graphicsView_6.setObjectName(u"graphicsView_6")
        self.graphicsView_6.setGeometry(QRect(630, 530, 271, 201))
        self.graphicsView_6.setAutoFillBackground(True)
        self.graphicsView_6.setStyleSheet(u"background-color: rgb(225, 225, 225);")
        brush3 = QBrush(QColor(255, 124, 234, 255))
        brush3.setStyle(Qt.NoBrush)
        self.graphicsView_6.setBackgroundBrush(brush3)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(330, 500, 191, 31))
        self.label_11.setFont(font1)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(630, 500, 191, 31))
        self.label_12.setFont(font1)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(440, 150, 191, 31))
        self.label_13.setFont(font1)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(950, 240, 231, 41))
        self.pushButton_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(182, 41, 16);")
        self.lcdNumber_9 = QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setObjectName(u"lcdNumber_9")
        self.lcdNumber_9.setGeometry(QRect(950, 180, 191, 41))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(950, 80, 221, 51))
        self.progressBar.setValue(24)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(950, 150, 121, 31))
        self.label_14.setFont(font1)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(1150, 190, 21, 31))
        self.label_15.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1265, 21))
        self.menuSummary = QMenu(self.menubar)
        self.menuSummary.setObjectName(u"menuSummary")
        self.menuIMU = QMenu(self.menubar)
        self.menuIMU.setObjectName(u"menuIMU")
        self.menuDocking = QMenu(self.menubar)
        self.menuDocking.setObjectName(u"menuDocking")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuSummary.menuAction())
        self.menubar.addAction(self.menuIMU.menuAction())
        self.menubar.addAction(self.menuDocking.menuAction())


        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Satellite overview", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Roll", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Yaw", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Orientation", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Other Parameters", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Temperature", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Angular Velocity", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Connection Overview", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Battery", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Connection Parameters", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Baud Rate", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Angular Velocity", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Orientation Visualizer", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Temperature Visualizer", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"View from Camera", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Shut Down", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Voltage", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.menuSummary.setTitle(QCoreApplication.translate("MainWindow", u"Summary", None))
        self.menuIMU.setTitle(QCoreApplication.translate("MainWindow", u"IMU", None))
        self.menuDocking.setTitle(QCoreApplication.translate("MainWindow", u"Docking", None))
    # retranslateUi

